
import "./globals.css";
import ThemeProvider from "@/context/ThemeProvider";

export const metadata = {
  title: "ANGIRA ART EXPORTS WEBSITE DESIGN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <ThemeProvider>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}